name: Canary-Build

on:
  workflow_dispatch:

permissions:
  contents: read   # To checkout the repository
  packages: write  # To push Docker images to GHCR

jobs:
  build-canary:
    name: Build Canary
    uses: ./.github/workflows/action-docker.yml
    with:
      version_tag: canary
      source_branch: ${{ github.ref_name }}
      is_latest: false
      title: dockman
      dockerfile: pkg/docker/Dockerfile
    secrets: inherit
